apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-demo
  namespace: demo-apps
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: metrics-demo
  endpoints:
    - port: web
      path: /metrics
      interval: 15s