apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-api
  namespace: demo-apps
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: orders-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s