apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: demo-apps
type: Opaque
stringData:
  POSTGRES_USER: orders_api
  POSTGRES_PASSWORD: "troque-essa-senha-lab"
  POSTGRES_DB: ordersdb
