apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: lab
  source:
    repoURL: https://github.com/ElizaAugusta4/lab-testes.git
    targetRevision: main
    path: helm/generic-app
    helm:
      valueFiles:
        - ../../application-manifests/dev/demo-apps/hello-app/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
