{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.serviceMonitor.releaseLabel }}
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
