apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab
  namespace: argocd
spec:
  description: Projeto do lab de observabilidade (GKE + Prometheus + Loki + apps)
  sourceRepos:
    - "https://github.com/ElizaAugusta4/lab-testes.git"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
  destinations:
    - namespace: demo-apps
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
